component:
  name: rblxkeysys
  type: service
  language: python
  version: "1.0.0"

resources:
  cpu: 100m
  memory: 256Mi

endpoints:
  - path: /encrypt
    method: POST
  - path: /decrypt
    method: POST

dependencies:
  - name: cryptography
    version: "43.0.0"
  - name: flask
    version: "3.0.3"

build:
  language: python
  baseImage: python:3.8-slim

runtime:
  entryPoint: server.py
  port: 8080